<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1**
 1. subsetting: *select a specific portion of data from a larger dataset*
 2. indexing: pick one element from the list using its allocated index
 3. slicing: pick a range of data *(elements)* from the list
 4. masking: use specific conditions to only show a range of data from the list
    

In [23]:
#Exercise 

import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
list_number=np_array_2d[:,0]
list_number_int=list_number.astype(int)
list_a=list_number_int%2
final_list=np_array_2d[list_a==1,1]
print(final_list)

['A' 'C' 'E' 'G' 'I']


In [27]:
#Exercise 3

np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
np_array[np_array<50]=-1
np_array[np_array>50]=1
np_array[np_array==50]=0
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
